# Generated by Django 5.1.5 on 2025-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_alter_clientpersoninfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientpersoninfo",
            options={
                "verbose_name": "Персональную информацию",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AddField(
            model_name="clientpersoninfo",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус заявки"),
        ),
    ]
