# Generated by Django 5.1.5 on 2025-01-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_alter_clientpersoninfo_preferred_communication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandvacancy",
            name="brand_id",
        ),
        migrations.RemoveField(
            model_name="brandvacancy",
            name="city_id",
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="database.brandstore",
                verbose_name="Брэнд магазина",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="database.city",
                verbose_name="Город",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clientpersoninfo",
            name="preferred_communication",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("phone", "Телефон"),
                ],
                default="phone",
                max_length=10,
                verbose_name="Предпочитаемый способ связи",
            ),
        ),
        migrations.AddIndex(
            model_name="brandvacancy",
            index=models.Index(fields=["city"], name="database_br_city_id_ba0984_idx"),
        ),
        migrations.AddIndex(
            model_name="brandvacancy",
            index=models.Index(fields=["brand"], name="database_br_brand_i_c67169_idx"),
        ),
    ]
