# Generated by Django 5.1.5 on 2025-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvacancy",
            name="vacancy_name_ky",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Название вакансии"
            ),
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="vacancy_name_ru",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Название вакансии"
            ),
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="vacancy_name_tg",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Название вакансии"
            ),
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="vacancy_name_uz",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Название вакансии"
            ),
        ),
    ]
