# Generated by Django 5.1.5 on 2025-01-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_rename_client_clientpersoninfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpersoninfo",
            name="preferred_communication",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                default="phone",
                max_length=10,
                verbose_name="Предпочитаемый способ связи",
            ),
        ),
        migrations.AddField(
            model_name="clientpersoninfo",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
