# Generated by Django 5.1.5 on 2025-01-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_alter_clientpersoninfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpersoninfo",
            name="preferred_communication",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "Whatsapp"),
                    ("phone", "Phone"),
                ],
                default="phone",
                max_length=10,
                verbose_name="Предпочитаемый способ связи",
            ),
        ),
    ]
