# Generated by Django 5.1.5 on 2025-01-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_remove_brandvacancy_brand_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("ky", "Киргизский"),
                            ("ru", "Русский"),
                            ("tg", "Таджитский"),
                            ("uz", "Узбекский"),
                        ],
                        max_length=2,
                        verbose_name="Код языка",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "unique_together": {("city", "language_code")},
            },
        ),
    ]
