# Generated by Django 5.1.5 on 2025-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0010_citytranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="citytranslation",
            name="translation",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Перевод"
            ),
        ),
    ]
