# Generated by Django 5.1.5 on 2025-01-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_citytranslation_translation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citytranslation",
            options={
                "verbose_name": "Перевод городов",
                "verbose_name_plural": "Переводы городов",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="city_name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Название города"
            ),
        ),
        migrations.AlterField(
            model_name="citytranslation",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="database.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="citytranslation",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("ky", "Киргизский"),
                    ("ru", "Русский"),
                    ("tg", "Таджитский"),
                    ("uz", "Узбекский"),
                ],
                max_length=2,
                verbose_name="Языка",
            ),
        ),
        migrations.CreateModel(
            name="BrandVacancyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translation",
                    models.CharField(max_length=128, verbose_name="Перевод"),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("ky", "Киргизский"),
                            ("ru", "Русский"),
                            ("tg", "Таджитский"),
                            ("uz", "Узбекский"),
                        ],
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="database.brandvacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод",
                "verbose_name_plural": "Перевод",
                "unique_together": {("vacancy", "language_code")},
            },
        ),
    ]
