# Generated by Django 5.1.5 on 2025-01-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0012_alter_citytranslation_options_alter_city_city_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название магазина"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сайт магазина",
                "verbose_name_plural": "Сайты Магазинов",
            },
        ),
        migrations.RemoveField(
            model_name="brandvacancy",
            name="brand",
        ),
        migrations.RemoveIndex(
            model_name="brandvacancy",
            name="database_br_brand_i_c67169_idx",
        ),
        migrations.AddField(
            model_name="brandvacancy",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="database.site",
                verbose_name="Сайт магазина",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="brandvacancy",
            index=models.Index(fields=["site"], name="database_br_site_id_48da74_idx"),
        ),
        migrations.DeleteModel(
            name="BrandStore",
        ),
    ]
