# Generated by Django 5.1.5 on 2025-01-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0013_site_remove_brandvacancy_brand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientpersoninfo",
            old_name="phone",
            new_name="client_phone",
        ),
        migrations.AlterField(
            model_name="brandvacancy",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="database.site",
                verbose_name="Сайт",
            ),
        ),
    ]
